# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Christoffer Hauthorn
email: christoffer@hauthorn.me
description: > # this means to ignore newlines until "baseurl:"
  My name is Christoffer Hauthorn Boisen, and I'm one of the technical co-founders of Emplate ApS and a Computer Science student at Aarhus University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hauthorn.me" # the base hostname & protocol for your site
twitter_username: ChristofferHB
github_username:  hauthorn
permalink: /:year/:month/:day/:title
# Build settings
markdown: kramdown
